name: Go

on:

  workflow_dispatch:


jobs:
  check:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]
      fail-fast: false 
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
         access_token: ${{ github.token }}
         workflow_id: ${{ github.event.workflow.id }}
         ignore_sha: true


